language: node_js
node_js:
  - '0.11'
install:
  - curl -s https://gist.githubusercontent.com/philopon/d45eb98d5976c6531217/raw/download-latest-purescript.sh | bash
  - tar xvf linux64.tar.gz
  - export PATH=`pwd`/purescript:$PATH
  - npm install
  - bower update
